server:
  port : 8088

spring:
  profiles:
      active: pro

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# spring-security请求地址
token:
  url: http://localhost:8088/oauth/token

# spring-boot-actuator敏感信息验证开关
management:
  security:
    enabled: false
  context-path: /actuator

---
spring:
  profiles: dev
ms:
  db:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/risk_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    maxActive: 500

---
spring:
  profiles: pro
ms:
  db:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/risk_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: leee
    password: cGF0cml3mlZWU=
    maxActive: 500
